Firebase lagging issues
vycius/NMAkademija pull request #72
Opened 2017-01-06 21:59 UTC by vycius

* Improved `FirebaseRealtimeApi` with async call and simplified logic;
* All adapters got stable id;

2017-01-06 22:56 UTC, gediminasel commented on app/src/main/java/com/nmakademija/nmaakademija/MainActivity.java
> +        viewPager.setOffscreenPageLimit(0);
I think you cant do that.
`Requested offscreen page limit 0 too small; defaulting to 1`

2017-01-06 23:07 UTC, gediminasel requested changes
- Timer doesn't work. I think you need to check 
`if (countDownTimer != null)
      countDownTimer.cancel();` before creating new timer onTimeUntilSessionLoaded.
- `ViewPager.setOffscreenPageLimit(param);` param must be >0

2017-01-06 23:35 UTC, gediminasel commented on app/src/main/java/com/nmakademija/nmaakademija/MainActivity.java
> +        viewPager.setOffscreenPageLimit(0);
warn : `Requested offscreen page limit 0 too small; defaulting to 1`

2017-01-07 08:48 UTC, vycius commented
Fixed both issues

2017-01-07 09:10 UTC, gediminasel approved these changes

2017-01-07 10:04 UTC, merged